[CmdletBinding(SupportsShouldProcess)]param([Parameter(Mandatory)][string]$ApiUrl,[Parameter(Mandatory)][string]$Manifest,[string]$Username=$env:MEDIAWIKI_USERNAME,[string]$Password=$env:MEDIAWIKI_PASSWORD,[switch]$AddSemanticBreadcrumbs,[string]$BreadcrumbProperty='Has parent page')
$ErrorActionPreference='Stop'; $m=Get-Content $Manifest -Raw|ConvertFrom-Json
if($PSVersionTable.PSVersion.Major -lt 7){throw 'Run Import-MediaWikiManifest.ps1 with PowerShell 7 (pwsh) to preserve UTF-8 content.'}
$s=New-Object Microsoft.PowerShell.Commands.WebRequestSession
function Api([hashtable]$p,[switch]$Post){$p['format']='json';if($Post){Invoke-RestMethod $ApiUrl -Method Post -Body $p -WebSession $s}else{Invoke-RestMethod "${ApiUrl}?$(( $p.GetEnumerator()|%{'{0}={1}'-f $_.Key,[uri]::EscapeDataString([string]$_.Value)})-join'&')" -WebSession $s}}
if($Username -or $Password){if(-not($Username -and $Password)){throw 'Username and Password must both be supplied'};$lt=(Api @{action='query';meta='tokens';type='login'}).query.tokens.logintoken;$login=Api @{action='login';lgname=$Username;lgpassword=$Password;lgtoken=$lt} -Post;if($login.login.result -ne 'Success'){throw 'MediaWiki login failed'}}
$pages=@((Api @{action='query';list='allpages';aplimit=1}).query.allpages); if($pages.Count){throw 'Target wiki is not blank; refusing to overwrite pages.'}
$map=@{};foreach($x in @($m.page_mapping)){$map[[string]$x.pageid]=$x};$ns=@($m.namespace_mapping|? create_if_missing);if($ns){$cfg=@('// Generated namespace declarations')+@($ns|%{'$wgExtraNamespaces['+$_.destination_id+'] = '''+$_.destination_name+''';'});$cfg|Set-Content (Join-Path (Split-Path $Manifest) 'namespace-settings.php') -Encoding utf8;Write-Host 'Created namespace-settings.php; apply it before importing pages.'}
$titleMap=@{};foreach($x in $m.pages){$d=$map[[string]$x.pageid];if($d -and $d.destination_namespace -and $x.ns -ne 6){$titleMap[$x.title]="$($d.destination_namespace):$($d.destination_title)"}}
function Rewrite-Links([string]$text){return [regex]::Replace($text,'\[\[([^\[\]|#]+)(#[^\]|]*)?(\|[^\]]*)?\]',{param($match)$target=$match.Groups[1].Value.Trim();if($titleMap.ContainsKey($target)){"[[$($titleMap[$target])$($match.Groups[2].Value)$($match.Groups[3].Value)]]"}else{$match.Value}})}
$t=(Api @{action='query';meta='tokens';type='csrf'}).query.tokens.csrftoken
foreach($p in $m.pages){$d=$map[[string]$p.pageid];$title=if($d -and ($d.destination_title -or $d.title)){if($d.destination_title){$d.destination_title}else{$d.title}}else{$p.title};$parent='';if($d.parent_path){$parent="$($d.parent_path.Trim('/'))";$title="$parent/$title"};$namespace=if($d.destination_namespace){$d.destination_namespace}elseif($d.namespace){($m.namespace_mapping|? destination_id -eq $d.namespace|select -First 1).destination_name};if($namespace){$title="$namespace`:$title"};$text=Rewrite-Links $p.source;if($AddSemanticBreadcrumbs -and $parent){$parentTitle=if($namespace){"$namespace`:$parent"}{$parent};$text="[[${BreadcrumbProperty}::$parentTitle]]`n`n$text"};if($PSCmdlet.ShouldProcess($title,'Create page')){$r=Api @{action='edit';title=$title;text=$text;token=$t} -Post;if($r.error){throw "Failed to create '$title': $($r.error.info)"}}}
Write-Host "Created $($m.pages.Count) pages. Files remain available from manifest assets for upload."
