[CmdletBinding()]
param([Parameter(Mandatory)][string]$Manifest,[string]$Decisions='wiki-organisation.json',[switch]$Interactive,[switch]$WholesaleSupport,[switch]$WhatIf)
$ErrorActionPreference='Stop';$m=Get-Content $Manifest -Raw|ConvertFrom-Json
$state=if(Test-Path $Decisions){Get-Content $Decisions -Raw|ConvertFrom-Json}else{[pscustomobject]@{decisions=@();questions=@()}}
$done=@{};foreach($d in @($state.decisions)){$done[[string]$d.pageid]=$d}
if($WholesaleSupport){$pages=@($m.pages|? ns -eq 0);$used=@{};$ds=@();foreach($p in $pages){$k=$p.title.ToLowerInvariant();$used[$k]=1+($used[$k]??0);$name=if($used[$k]-eq 1){$p.title}else{"$($p.title) ($($used[$k]))"};$parent=if($p.title -match '/'){ $p.title.Substring(0,$p.title.LastIndexOf('/')) }else{'Main Page'};$leaf=if($p.title -match '/'){ $p.title.Substring($p.title.LastIndexOf('/')+1) }else{$p.title};$ds+=[pscustomobject]@{pageid=$p.pageid;source_title=$p.title;destination_namespace='Wholesale_Support';parent_path=$parent;destination_title=$leaf;status='pending'}};$ds+=[pscustomobject]@{pageid=-1;source_title='__root__';destination_namespace='';parent_path='';destination_title='Main Page';source="== Knowledge namespaces ==`n* [[Wholesale_Support:Main Page|Wholesale Support]]";status='generated'};$m.pages+= [pscustomobject]@{pageid=-1;title='Main Page';ns=0;source="== Knowledge namespaces ==`n* [[Wholesale_Support:Main Page|Wholesale Support]]"};$m|Add-Member -Force NoteProperty page_mapping $ds;$m|Add-Member -Force NoteProperty namespace_mapping @([pscustomobject]@{destination_name='Wholesale_Support';destination_id=100;create_if_missing=$true});$out=Join-Path (Split-Path $Manifest) 'manifest-namespaced.json';$m|ConvertTo-Json -Depth 30|Set-Content $out -Encoding utf8;Write-Host "Wrote $out";exit}
function Save-State{$state|ConvertTo-Json -Depth 20|Set-Content $Decisions -Encoding utf8}
foreach($p in $m.pages){$key=[string]$p.pageid;if($done.ContainsKey($key)){continue};$summary=($p.source -replace '\s+',' ').Trim();if($summary.Length -gt 180){$summary=$summary.Substring(0,180)+'...'}
  if($Interactive){Write-Host "`n[$($p.pageid)] $($p.title) (ns $($p.ns))`n$summary"; $ns=Read-Host 'Destination namespace name (blank = keep)';$parent=Read-Host 'Parent page/path (blank = none; e.g. Policies/HR)';$title=Read-Host 'Destination title (blank = keep)';$note=Read-Host 'Decision note (optional)'}else{$ns='';$parent='';$title='';$note=''}
  $d=[pscustomobject]@{pageid=$p.pageid;source_title=$p.title;destination_namespace=$ns;parent_path=$parent;destination_title=if($title){$title}else{$p.title};note=$note;status='pending'};$state.decisions+=@($d);Save-State;Write-Host "Saved decision for $($p.title)"}
$decisionDir=Split-Path $Decisions -Parent;$out=if([string]::IsNullOrWhiteSpace($decisionDir)){'manifest-namespaced.json'}else{Join-Path $decisionDir 'manifest-namespaced.json'};$o=Get-Content $Manifest -Raw|ConvertFrom-Json;$o|Add-Member -Force NoteProperty page_mapping @($state.decisions);$next=100;$o|Add-Member -Force NoteProperty namespace_mapping @($state.decisions|? destination_namespace|select -Expand destination_namespace -Unique|%{[pscustomobject]@{destination_name=$_;destination_id=$next++;create_if_missing=$true}});$o|ConvertTo-Json -Depth 30|Set-Content $out -Encoding utf8;Write-Host "Wrote $out";if($WhatIf){Write-Host 'WhatIf: no wiki writes performed.'}
